### ISSUE TITLE
Try to decode certain text fields correctly

### ISSUE THREAD

**Issue by BoldMonday** [LucasFonts/vfbLib#12]
Thank you for creating this. It is really great!

It appears that currently vfblib does not decode certain text fields correctly, resulting in garbled text in the converted UFO file:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/13793769/208857961-201174a1-f65f-4d4d-b9b2-8b4819d63f1c.png">

<img width="593" alt="image" src="https://user-images.githubusercontent.com/13793769/208856733-49a1f7c8-fba7-48ff-a2d0-fc111d6a2213.png">

I know this is tricky because different versions of FontLab on different platforms might encode certain text fields differently. FL5.0.x on MacOS used Mac Roman encoding for example. But since FL5.1.x our internal tools always assume the following text fields to be in UTF-8 encoding:

**• copyright**
f.naked().copyright.decode('utf-8')
**• trademark**
f.naked().trademark.decode('utf-8')
**• manufacturer**
f.naked().source.decode('utf-8')
**• designer**
f.naked().designer.decode('utf-8')
**• description**
f.naked().notice.decode('utf-8')
**• license**
f.naked().license.decode('utf-8')
**• note**
f.naked().note.decode('utf-8')

**Comment by jenskutilek** [comment]
Thank you! I’ll check next year :)

**Comment by jenskutilek** [comment]
@BoldMonday would you have a sample file with UTF-8 encoded fields by any chance?

I just tried with FL5 on Windows, and there, when I enter any character outside of Windows-1252, it is actually saved as a ? in the VFB ...

**Comment by BoldMonday** [comment]
@jenskutilek Sure! Have a look at the IBM Plex vfb files at 
https://github.com/IBM/plex/tree/master/IBM-Plex-Sans/sources/instances/truetype
The trademark field contains a registered® symbol.

<img width="919" alt="image" src="https://user-images.githubusercontent.com/13793769/225555406-7ba0ef40-af66-4c33-825b-88a06054b827.png">

**Comment by jenskutilek** [comment]
Fixed via 9c02a12c830d0bf482711cd99fe7f3b973aea16f.

**Comment by jenskutilek** [comment]
You can add the option `-u` to `vfb3ufo` to interpret (some) strings from the VFB as UTF-8.
