### ISSUE TITLE
Kerning class names changed upon export

### ISSUE THREAD

**Issue by frankrolf** [LucasFonts/vfbLib#22]
I am a happy user of `vfb3ufo`, and have nothing but praise.

A minor irk – when I export a VFB, it seems the kerning group names are changed to correspond to their key glyph (FontLab invention). Some follow-up steps in my workflow look for specific tags in the group name (`ARA`, for example, to make RTL kerning), so the changed group name basically means crucial information lost for me.

I can work my way around this by using https://github.com/adobe-type-tools/python-modules/blob/main/kernExport.py , but I’d rather not open FL anymore ;-)

Please let me know if I should attempt a PR with this change.

**Comment by jenskutilek** [comment]
Fair point. I guess I intended to preserve the key glyph information, but that can be done in another way, e.g. by a private lib entry.

Would you prefer to keep the name exactly as it is in the VFB, or get rid of the underscore at the beginning of kerning group names?

**Comment by jenskutilek** [comment]
Can you try this branch? https://github.com/LucasFonts/vfbLib/tree/kerning-group-names

**Comment by jenskutilek** [comment]
Kerning groups now keep their name (other than being prefixed with `public.kern...` in version [0.5.4](https://github.com/LucasFonts/vfbLib/releases/tag/v0.5.4)

**Comment by frankrolf** [comment]
Works tremendously! Thank you! 🥰

**Comment by frankrolf** [comment]
Thanks again for this work!

A purely aesthetic concern:
AFAIK, in FontLab world, all kerning group names start with `_` – for example, `_J_UC_RIGHT`.

This group name is now converted to `public.kern2._J_UC_RIGHT` – but might as well be `public.kern2.J_UC_RIGHT`

**Comment by frankrolf** [comment]
Huh – disregard. Looking at another project, I don’t see the same behavior. I’ll keep you posted.

**Comment by jenskutilek** [comment]
Groups in FL5's Class Panel are are differentiated by their prefix, `_` for kerning groups, `.` for metrics groups, and anything else for OpenType classes. Kerning groups generated by other tools – Metrics Machine, KLTF Kern Feature, use(d) different naming conventions. For me, either would be fine, keeping or dropping the underscore. One could argue that `public.kern[12]` is the equivalent of the underscore, so it should go ;)
