### ISSUE TITLE
can vfbLib write from ufo -> vfb? 

### ISSUE THREAD

**Issue by typemytype** [LucasFonts/vfbLib#47]
is it possible to compile back to vfb?

**Comment by jenskutilek** [comment]
Compiling data entries in a vfb structure is currently supported in a limited way. Only [glyph data](https://github.com/LucasFonts/vfbLib/blob/main/Lib/vfbLib/compilers/glyph.py) can be compiled right now.

It could be extended to other parts, as most of the VFB structure is clear. There are some parts in the header that I don't know what they are, so I don't touch them. Compilers for most other types of data could be implemented, but it is just a PITA to go through them all. One would have to look at the corresponding parser code and reverse it.

Glyph compilation is implemented as far as needed to for pen protocol access to vfb glyphs, which in turn at the moment is only used by [vfbcu2qu](https://github.com/LucasFonts/vfbLib/blob/main/Lib/vfbLib/cu2qu.py) for cubic to quadratic conversion with cu2qu.

```
vfbcu2qu -h
usage: vfbcu2qu [-h] [-p PATH] [-fo] [-m MAX_ERR_EM] inputpath [outputpath]

VFB Cubic to Quadratic Converter Copyright (c) 2023 by LucasFonts Build 2023-12-20

positional arguments:
  inputpath             input file path (.vfb)
  outputpath            output file path (.vfb)

options:
  -h, --help            show this help message and exit
  -p PATH, --path PATH  output folder
  -fo, --force-overwrite
                        force overwrite
  -m MAX_ERR_EM, --max-err-em MAX_ERR_EM
                        Maximum allowed error, relative to the font's units per em.
```

**Comment by typemytype** [comment]
Thanks! And maybe its not needed after all, FL can import UFOs...
