### ISSUE TITLE
Some components get collapsed to 0% vertical height

### ISSUE THREAD

**Issue by BoldMonday** [LucasFonts/vfbLib#94]
Attached vfb file contains a number of components.

<img width="395" alt="image" src="https://github.com/user-attachments/assets/a5f8b78a-90cd-4be9-9464-e264f1182a9f">

During conversion to UFO with the latest version of vfbLib (v0.7.0) they get collapsed to a vertical height of 0%.

<img width="564" alt="image" src="https://github.com/user-attachments/assets/8ceee091-4d0d-4eaa-8727-3f0e02432068">

Strangely this only happens to certain components but I'm unable to determine what is the culprit.

[Component-test.vfb.zip](https://github.com/user-attachments/files/16428207/Component-test.vfb.zip)

**Comment by jenskutilek** [comment]
An interesting case ...

In your VFB, the y scale factor of the affected components is saved as `ffffffff ffffef3f`, or 0.9999999999999999, but in FL5 it is shown as 100.0.

The value 0.9999999999999999 is written verbatim to ufoLib2/fontTools.ufoLib, which stays intact until it ends up as an element tree XML attribute. Even then, when I get the XML string at that point, it is printed as 

```xml
b'<component base="eight.osf" yScale="0.9999999999999999" xOffset="-5"/>'
```

But then somehow when it is actually written to the glif file, it's suddenly `yScale="0"` ...?

I couldn't find out what the maximum float precision in UFO is, but when I round the scale values e.g. to 10 decimals, the number in question is finally interpreted as 1.

**Comment by justvanrossum** [comment]
I can't convert the attached font. Am I doing something wrong?

```
$ vfb3ufo Component-test.vfb
VFB3UFO Converter
Copyright (c) 2024 by LucasFonts
Build 2024-06-04
Reading file Component-test.vfb ...
Source file was successfully read in 1 ms.
Parse error for data: openTypeFeatures; 0d0a
Parser class: OpenTypeStringParser
Traceback (most recent call last):
  File "/Users/just/code/git/vfbLib/venv/bin/vfb3ufo", line 8, in <module>
    sys.exit(vfb2ufo())
             ^^^^^^^^^
  File "/Users/just/code/git/vfbLib/Lib/vfbLib/cmdline.py", line 194, in vfb2ufo
    vfb.decompile()
  File "/Users/just/code/git/vfbLib/Lib/vfbLib/vfb/vfb.py", line 122, in decompile
    entry.decompile()
  File "/Users/just/code/git/vfbLib/Lib/vfbLib/vfb/entry.py", line 212, in decompile
    self.decompiled = self.parser().parse(
                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/just/code/git/vfbLib/Lib/vfbLib/parsers/base.py", line 45, in parse
    return self._parse()
           ^^^^^^^^^^^^^
  File "/Users/just/code/git/vfbLib/Lib/vfbLib/parsers/text.py", line 83, in _parse
    while not lines[-1]:
              ~~~~~^^^^
IndexError: list index out of range
```

**Comment by BoldMonday** [comment]
@justvanrossum  Using Python 3.9.7 is did the following:

```
$ vfb3ufo -fo -nops ./Component-test.vfb               
VFB3UFO Converter
Copyright (c) 2024 by LucasFonts
Build 2024-06-04
Reading file Component-test.vfb ...
Source file was successfully read in 2 ms.
Interpreting binary data took 5 ms.
Processing font: Untitled Regular, master 0
```

**Comment by justvanrossum** [comment]
Big step further: it is ufonormalizer that is causing this.

**Comment by jenskutilek** [comment]
> I can't convert the attached font. Am I doing something wrong?
> 
> ```
> IndexError: list index out of range
> ```

Oops ... that’s an unrelated bug triggered by the OpenType feature code being empty in the VFB. Fixed via a010882.

**Comment by jenskutilek** [comment]
> Big step further: it is ufonormalizer that is causing this.

Ouch! I had forgotten about ufonormalizer being used. Thank you @justvanrossum for investigating!

A workaround is in 329b9c8 and the [v0.7.1 release](https://github.com/LucasFonts/vfbLib/releases/tag/v0.7.1) which rounds the scale values to 15 decimals.

**Comment by BoldMonday** [comment]
Thanks for the swift response! 🙏
